### ISSUE TITLE
请教下client以及server_dist如何部署

### ISSUE THREAD

**Issue by webjohnjiang** [youzan/zan-template#1]
您好，想咨询2个问题:

1. client目录是用来放前端SPA单页应用的代码文件的吗？ 那这里面的单页应用是通过前端自己的工作流程进行编译的吗? 比如如何使用Vue2进行开发、部署,  就在client/h5里面重新自己初始化一个vue项目，然后webpack编译就行吗？ 编译后的结果怎么部署呢?

2. zan-template最终部署时，是不是这样的步骤:  先执行zan babel，然后把server_dist放到服务器，然后用supervisor来启动？

3. zan htmlmin 这个命令是编译后端模板是吗？可是我检查了下server/view 和 server_dist/view，发现并没有任何区别，不知道为什么?

**Comment by kk0829** [comment]
@cuiyongjian 
问题1：前端不管用什么框架和打包编译工具，静态资源最后应该是上传到 CDN，然后生成 version 文件，version 文件是放在 server/config 目录下
问题2：是的，服务端代码部署前是执行 zan babel && zan htmlmin ，supervisor 启动命令用的是 node bin/start.js
问题3：这是框架 ZanNode 的一个 bug，已经修复，你升级到最新版即可；

**Comment by webjohnjiang** [comment]
@kk0829  能否详细讲解下前端单页的开发工作流程。

1. 因为我用这套脚手架时，由于vue项目放在client目录下，但编辑器vscode打开的是整个zen-node项目，而且git管理的也是整个zen-node项目。 所以导致vue项目里的editorconfig, eslintrc,等配置都不好用了，对编辑器起作用的也是zen-node根目录下的eslintrc等。 （felint也存在这问题）
是不是前端和后端要分开进行开发和git管理。

2. 另外想问下，部署静态资源生成version，这个流程怎么操作呢？ 为什么放在server/config下server就能跟client联系起来了？

问题有点多，非常不好意思。如果有详细文档，也可以给我丢个文档我自己研究。 其实我的问题是： 利用zan-node这个脚手架开发前后端分离的应用时的最佳实践是什么？

或许前后端分离的话，就不应该用zen-node?

**Comment by webjohnjiang** [comment]
作者微信耐心解答了... 感谢作者
